### ISSUE TITLE
Split the royalty

### ISSUE THREAD

**Issue by loic-combis** [dievardump/EIP2981-implementation#7]
Hi there!

Thanks for showing howe to implement royalties on ERC721 & ERC1155 tokens.
Is there a way to split the royalty between several "owners" while respecting the EIP-2981 standard?

**Comment by dievardump** [comment]
ERC2981 can only have one recipient, so you'd need to:

- create a "splitter contract" (for example through: https://collab-splitter.org)
- set the splitter contract as royaltiesRecipient
