### ISSUE TITLE
Are royalties mandatory in these contracts?

### ISSUE THREAD

**Issue by rom102393** [dievardump/EIP2981-implementation#9]
Hello and thanks for the great work.
And I tried to test it. I deployed two contracts (ERC721WithContractWideRoyalties.sol and ERC721WithRoyalties.sol) and there were no errors with it. But test opensea shows that these royalties are not mandatory. And that's why I have a question, should it be like this or did I do something wrong? Please help me understand this. Thank you.

**Comment by dievardump** [comment]
Hey @rom102393 

This implementation was created long before the OpenSea blocking stuff happened. It is only a basic implementation of ERC2981 and does not care about marketplaces doing weird stuff.

If you need the support of the Operator Registry then I invite you to look at the OperatorFilterRegistry repository and the examples they provide: https://github.com/ProjectOpenSea/operator-filter-registry/tree/main/src/example

 I am going to close that for now but feel free to comment if you need more info

**Comment by rom102393** [comment]
@dievardump Oh, now I understand. And thanks for the link. I'm a newbie, but I hope it's not too difficult to deploy such a contract. I'll try to learn it (Such a youtube tutorial would be helpful :)) Thanks again.

**Comment by dievardump** [comment]
The project I linked has a good README file and is available both on Forge and on NPM. 
Depending what stack you are using to develop, you should be able to easily install the package as a dependency
After that you will easily be able to copy the examples and create your own contracts with the OperatorFilter activated


Read the readme file / documentation of the project I linked, and you should be able to quickly use it

**Comment by rom102393** [comment]
I will try to. While I was doing it on my knee, the remix ide. Thank you very much.

**Comment by dievardump** [comment]
Oh I would not use REMIX if I were you. It's ok to test things quickly, but not to really develop projects.

I suggest you learn how to use [hardhat](https://hardhat.org/) with the [hardhat-deploy](https://github.com/wighawag/hardhat-deploy) plugin
This is way better than remix

**Comment by rom102393** [comment]
Well. It is convincing. :)
